### PR TITLE
Allow function to be passed as a callback and throw error if callback has not been found

### PR DESCRIPTION
**Pull request by kamilogorek**
Related: https://github.com/AmpersandJS/ampersand-view/issues/37 and https://github.com/AmpersandJS/ampersand-view/issues/38

### CODE REVIEW

**Comment by latentflip** [comment]
I haven't tried this, but based on the code from my phone big +1 from me.

Only concern is that this module was

**Comment by latentflip** [comment]
I haven't tried this, but based on the code from my phone big +1 from me.

Only concern is that this module was originally just a fork of component/events and now we're modifying it, but this seems worth it to me.

**Comment by kamilogorek** [comment]
We can always create `ampersand-events` to suit our needs.

**Comment by jrmyio** [comment]
Can this please be merged or determined if there is going to be an "ampersand-events"?

**Comment by dminkovsky** [comment]
Yes please, or please change the docs.

It's fine not to have a feature, but it sucks of the docs tell you the feature exists and it doesn't, especially if it's a feature from Backbone. Made me feel crazy until I zero-ed in on the offending code and was like "yeah, that's not supporting functions". Then found these issues, which I didn't bother looking for due to the fact that I expected this feature from Backbone.

**Comment by dminkovsky** [comment]
And it's like, should be a test for this? Regardless of which convention is chosen: if the events hash does not support functions, it should throw a sensible error when trying to bind a function.

**Comment by dminkovsky** [comment]
@latentflip regarding:

> Only concern is that this module was originally just a fork of component/events and now we're modifying it, but this seems worth it to me.

Yeah, this is the kind of thing that preserving Backbone-parity for, I think, is totally worth forking from the fork. It's a fork after all!

And in terms of Backbone parity, the following also deviates from Backbone and would be great to bring back to the Backbone convention (from `ampersand-view` docs):

> "Omitting the selector causes the event to be bound to the view's root element (this.el)."

Maybe I'm too used to the Backbone events hash, but why would this be the behavior? I kinda get it, like, if you're not delegating then have the callback act like a normal DOM even binding. But, eh.

**Comment by HenrikJoreteg** [comment]
Sorry for the delay on this folks. Totally agree we should modify this to our needs. Also, +1 to tests. 

Let's make this what it needs to be instead of just a fork. Happy to ultimately create ampersand-dom-events once we figure this out. 

Also, of interest: https://github.com/AmpersandJS/ampersand-view/issues/73

**Comment by HenrikJoreteg** [comment]
i made a card for this on the roadmap: https://trello.com/c/EO6kWImO/40-make-ampersand-dom-events-to-address-various-issues-backbone-incompatibilities-with-https-github-com-henrikjoreteg-events

**Comment by johnloy** [comment]
This just bit me. I went through the same journey and wtf moment as Dmitry. It's easy enough for me to monkey-patch my project temporarily, but please at least update the docs until ampersand-dom-events is ready. Thanks in advance @kamilogorek!

**Comment by kamilogorek** [comment]
Shall we get it in @HenrikJoreteg?

**Comment by HenrikJoreteg** [comment]
yeah, sorry @kamilogorek. I just added you as a collaborator and owner on npm. Go for it.

**Comment by HenrikJoreteg** [comment]
actually, i'll just do it.

**Comment by HenrikJoreteg** [comment]
published as `events-mixin@1.2.0`

**Comment by johnloy** [comment]
@HenrikJoreteg @kamilogorek Thanks guys!

**Comment by kamilogorek** [comment]
Perfect, thanks Henrik!

**Pull request merged**
